### ISSUE TITLE
Conformance with https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

### ISSUE THREAD

**Issue by kink80** [softwaremill/sttp#1067]
Hi,
 I've found an issue in the URI parsing which I think does not follow the RFC.

The https://datatracker.ietf.org/doc/html/rfc3986#section-2.2 section explicitly mentions that "If data for a URI component would conflict with a reserved character's purpose as a delimiter, then the conflicting data must be percent-encoded before the URI is formed."

Now if the following input `https://someserver.com/file?content-type=application%2Fvnd.openxmlformats-officedocument.presentationml.presentation` gets piped into an uri like `uri"$myuri"` it comes back as `https://someserver.com/file?content-type=application/vnd.openxmlformats-officedocument.presentationml.presentation`.  Notice the forward slash in the `content-type` parameter.

Such request can't be successfully run with any of the backends but succeeds with curl, wget, plain java connection and so on.

Since the forward slash is a sub-delim it breaks the whole request, this is troublesome especially if the request contains a signature that's based on such parameter.

**Comment by adamw** [comment]
But `/` is not a delimiter in the query part?

**Comment by kink80** [comment]
That's right.
My question is then whether it should be changed/decoded during the parsing - as in should we not keep its original form?

**Comment by adamw** [comment]
Keeping the original form is tricky, as the `Uri` datatype keeps all of the components unencoded - without any knowledge of the encoded form. We can consider it for the next major revision of sttp, as changing anything in the uri would be backwards-incompatible.

You can change the encoding of particular segments using e.g. `querySegmentsEncoding`. I think `parsedUri.querySegmentsEncoding(x => URLEncoder.encode(x))` should give you the form you are looking for.

And finally - is there something wrong with `Uri`'s behavior wrt the spec?

**Comment by kink80** [comment]
The suggested workaround wouldn't be applicable for part(s) of the sttp client where the `Uri` gets used internally, wouldn't it?

This is especially troubling for `RetryAndFollowUpInterceptor`, if there was a redirect response that points to a pre-signed location whose signature had been computed using the raw form the request would inevitably fail.

For the behavior part, section https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.2.2 specifically mentions that only unreserved set of chars should be decoded when comparing URIs but doesn't state anything for the forward slash. 

I think that the section above, the behavior of other clients like curl, wget, java URI, Insomnia, browsers, etc. builds a strong case against decoding.

**Comment by adamw** [comment]
Yes, when the `Uri` is used internally this won't work.

I'm not sure I get the full picture, though. The linked section (https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.2.2) says that the URIs get normalized once decoded - so if some characters are unnecessarily encoded, they should be decoded and in the end we end up with the same string.

However, as I understand, there is some case when the behavior of sttp diverges from curl/wget etc? Can you post such a reproducing example so that I can test locally as well? Also, what is the `RetryAndFollowUpInterceptor` - I don't think this is from sttp's code base?

**Comment by kink80** [comment]
Sorry, I meant to say `FollowRedirectsBackend` instead of `RetryAndFollowUpInterceptor`, the latter is from the `OkHttp` codebase. 

@adamw  For the reproducing example - I don't have anything at hand but I'm happy to jump on a call if that works out for you.

**Comment by adamw** [comment]
Ah, well you can always create your own `FollowRedirectsBackend` and wrap your backend with it, this will disable the default one. But that's definitely a work-around, not a solution :)

I'm open to having a call, but earliest in September - as I'm heading out for vacation soon.

Maybe you'll be able to come up with a reproducing example so that we could  kickstart the conversation with some shared understanding of the problem :)

**Comment by kink80** [comment]
September works for me, I'll ping you once you're back.

**Comment by kink80** [comment]
PR'd at https://github.com/softwaremill/sttp/pull/1119

**Comment by kink80** [comment]
@adamw gentle nudge, is there anything in the PR you'd like me to follow up on?

**Comment by adamw** [comment]
@kink80 sorry I was away until today :) Looks good, though I think it can be simplified. Generally if you want to you want configure the `FollowRedirectsBackend`, you should wrap your backend with a new `FollowRedirectsBackend` - this effectively disables any other redirect backends that are down the line, and you don't need to have all of the FRB's options present in the backend options. I think here it should be possible to do the same?

The above should be probably documented here https://sttp.softwaremill.com/en/latest/conf/redirects.html, but well, another area to improve ;)

**Comment by kink80** [comment]
Ok then, I'll push it just to the `FRB` then.

**Comment by kink80** [comment]
@adamw done
