### ISSUE TITLE
Feature Request: Single Import Usage?

### ISSUE THREAD

**Issue by lihaoyi** [softwaremill/sttp#121]
Currently the getting started example is this:

```scala
import com.softwaremill.sttp._
implicit val backend = HttpURLConnectionBackend()
sttp.get(uri"http://httpbin.org/ip").send()
```

Any chance we could add a convenience import to avoid the `implicit val`?

```scala
// brings in an `implicit val backend = HttpURLConnectionBackend()` automatically
import com.softwaremill.sttp.default._
sttp.get(uri"http://httpbin.org/ip").send()
```

Would make sttp much more convenient to use from e.g. the Ammonite REPL

**Comment by adamw** [comment]
Interesting idea. Definitely possible - some changes would be needed (e.g. moving the contents of the package object to a trait, and extending it in both packages), but nothing major. Probably the package could be called sth indicating that it brings in a synchronous backend (`import com.softwaremill.sttp.sync._`?).

One worry I would have, though, is that using sttp in a REPL and in a "normal" application would be different. In REPL you would import the package that brings in the synchronous backend, while in a normal application you would import the one which requires a backend to be defined. Don't you think that this could confuse users?

A solution here could be to name the package so that it indicates that it's a "quick" or "REPL-only" solution, so maybe:

* `import com.softwaremill.sttp.quick._`
* `import com.softwaremill.sttp.repl._`

?

**Comment by lihaoyi** [comment]
Sure the exact package name doesn't matter to me, any of your suggestions work

**Comment by lihaoyi** [comment]
I'm not sure if there are other stateless backends too (e.g. an async one?) but for all the stateless ones it would make sense to add a default "no config" import to use them easily
