### ISSUE TITLE
Should use a global AsyncHttpClient for AsyncHttpClientCatsBackend

### ISSUE THREAD

**Issue by wb14123** [softwaremill/sttp#1357]
From the current document, seems the recommend way to use AsyncHttpClientCatsBackend is to create an IO and close it after usage:

```Scala
AsyncHttpClientCatsBackend[IO]().flatMap { backend =>
   ...
   backend.close()
 }

// or

AsyncHttpClientCatsBackend.resource[IO]().use { backend => ??? }
```

But this would create a new backend each time, which will result a new AsyncHttpClient, which will create/destroy multiple threads per request that affects performance. That's why AsyncHttpClient recommends a global instance instead of create and close it per request:

> AsyncHttpClient instances must be closed (call the close method) once you're done with them, typically when shutting down your application. If you don't, you'll experience threads hanging and resource leaks.
> 
> AsyncHttpClient instances are intended to be global resources that share the same lifecycle as the application. Typically, AHC will usually underperform if you create a new client for each request, as it will create new threads and connection pools for each

It would be fine though, if we can create a global `AsyncHttpClientCatsBackend` instead. But since it's an IO I don't know how to do it. Something like this would still result the creation of a new backend each time:

```Scala
object GlobalClient {
   val backend = AsyncHttpClientCatsBackend.resource[IO]()
}
```

**Comment by adamw** [comment]
Yes, you are right, a single backend should be created in an application. If the docs aren't clear on that, please point us which parts caused the misunderstanding :)

As for how to create a global backend using `Resource`s, you need to `use` the resource in your `Main` class; in the `use` body, you need to perform "DI" or however you structure your application - that is, create an object graph of the services, DAOs etc. And then you need to run the main app logic - it might mean e.g. accepting connections on an interface. So everything happens in side that `use` invocation, and it might not even ever terminate.

For a larger example on how this can be done see [bootzooka](https://github.com/softwaremill/bootzooka/blob/master/backend/src/main/scala/com/softwaremill/bootzooka/Main.scala), although it uses [autowire](https://github.com/softwaremill/macwire#autowire) for wiring, so you won't see the wiring done explicitly. But it's there, in the end you obtain a `Resource` with your dependencies created.

**Comment by wb14123** [comment]
Actually seems the backend returned by `AsyncHttpClientCatsBackend.usingClient[IO](asyncHttpClient)` does what I want: it can be used in `send` directly and return an IO. This is not mentioned in the doc as well. I can help add more details in the doc if needed.

**Comment by adamw** [comment]
@wb14123 This is described in a separate page: https://sttp.softwaremill.com/en/latest/backends/start_stop.html
The intention here was to capture this information once, as it applies to all backends, instead of repeating this on every backend page :)

Of course you don't need any kind of DI library for a simple app, it's just that was the example I had at hand. You'll probably be fine with a simple

```scala
AsyncHttpClientCatsBackend.resource.use { backend =>
  // your app logic here
}.unsafeRunSync()
```

The reason for the cats-effect vs Future backend differences is that coding styles differ when using both abstractions. WIth cats-effect, you typically want to capture **all** side effects as `IO`, because as `IO`s are lazily evaluated, you want these side effects to be evaluated when the `IO` is run, not when it is created. As a thread pool is allocated when creating a backend, this is a side-effecting operation. Futures, on the other hand, are evaluated right away, so there's no benefit from wrapping the backend's construction with a `Future`.

`AsyncHttpClientCatsBackend.usingClient[IO](asyncHttpClient)` uses an already allocated thread pool (in the client), so there's no need for the result to be wrapped in an `IO`.

**Comment by wb14123** [comment]
That make sense. I also found a mention in https://sttp.softwaremill.com/en/latest/backends/summary.html that says `Typically, a single backend instance is created for the lifetime of the application.`, somehow I missed it.

Will close the ticket since it answers my question.
