### ISSUE TITLE
opentracing-backend is no longer being built

### ISSUE THREAD

**Issue by nwaywood** [softwaremill/sttp#1511]
The latest version of `opentracing-backend` is `3.5.2` (https://mvnrepository.com/artifact/com.softwaremill.sttp.client3/opentracing-backend) but every other package under `com.softwaremill.sttp.client3` is up to `3.7.1` (example https://mvnrepository.com/artifact/com.softwaremill.sttp.client3/async-http-client-backend-cats-ce2).

Is it deliberate that `opentracing-backend` doesn't have new versions anymore? Or is this a bug?

**Comment by adamw** [comment]
Yes, that general implementation was broken. It's not possible unfortunately to create a "general" opentracing backend, as the way the context is propagated depends on the effect library. Currently we have an implementation for ZIO only (using their `FiberLocal`s)

**Comment by nwaywood** [comment]
@adamw so does that mean `opentracing-backend` won't be getting new versions anymore? Or will it still get new versions but with a different release cycle to the other packages?

**Comment by adamw** [comment]
Yes, it's simply not possible to create an opentracing backend generically so that it would work with any effect (Future, sync, cats-effect, zio). There's a ZIO implementation (https://sttp.softwaremill.com/en/latest/backends/wrappers/opentelemetry.html#tracing-zio), and trace4cats provides sttp integration (also in the same doc). But I don't think there's a working solution e.g. for `Future` (although maybe somehow using Kamon?)
