### ISSUE TITLE
cats-effect explicit dependency

### ISSUE THREAD

**Issue by mfirry** [softwaremill/sttp#1590]
Hi,
I've got this situation

build.sbt
```
    
    libraryDependencies ++= Seq( ...

    "com.softwaremill.sttp.client3" %% "async-http-client-backend-cats" % sttpVersion,
    "com.softwaremill.sttp.client3" %% "core" % sttpVersion,
    "com.softwaremill.sttp.client3" %% "circe" % sttpVersion,
```

and then in the code I was able to just have

```
import cats.effect.{ContextShift, IO}
AsyncHttpClientCatsBackend.resource[IO]().use { ...
```

In `build.sbt` I used to have `val sttpVersion = "3.0.0"`.
Today I changed it into `val sttpVersion = "3.8.2"` and now my cats-effect related imports are broken.

I suppose I need to have cats-effect among my dependencies.

So the question is: when did this change? 
Also, how do I know which version of cats-effect `sttp` requires?

As always, thanks for the hard work and amazing project!

**Comment by adamw** [comment]
Probably that's because at some point we moved to cats-effect 3 :) And you still have cats-effect 2 (I guess the imports for a major version of cats-effect shouldn't change?)

If you want to keep using ce2, use this artifact: `async-http-client-backend-cats-ce2` (https://sttp.softwaremill.com/en/latest/backends/catseffect.html#using-async-http-client)

Here's the exact ce3 version sttp 3.8.2 depends on: https://mvnrepository.com/artifact/com.softwaremill.sttp.client3/cats_3/3.8.2

**Comment by mfirry** [comment]
Makes sense. I'm not really using cats-effect really. Just using `AsyncHttpClientCatsBackend` which requires it.

Thanks!

**Comment by adamw** [comment]
On that note, you might want to consider moving to another backend: https://github.com/softwaremill/sttp/issues/1571

There's a couple of other options :)

**Comment by mfirry** [comment]
So what would be an alternative if I want to use cats-effect?
