### ISSUE TITLE
Type RequestT may be intimidating

### ISSUE THREAD

**Issue by julienrf** [softwaremill/sttp#1607]
Currently, `RequestT[U[_], T, -R]` takes three type parameters. One of them is a phantom type (`U[_]`), and another one models the “backend capabilities required by the request or response” (`R`).

This is very powerful, but in my opinion, it exposes unnecessary complexity for users interested in using the `SimpleHttpClient` added in #1545, for instance. I wonder if we could also provide a `Request` type specific to synchronous backends (so, without a notion of capabilities), and a builder system to differentiate between a partial request and a complete request (to avoid the need for a phantom type).

I believe that would expose a type that would be easier to work with for people only interested in doing synchronous requests on the JVM.

Here is an (untested) idea:

~~~ scala
trait RequestBuilder[A] extends RequestT[Empty, A, Any] {

  def cookie(n: String, v: String): RequestBuilder[A]
  def contentType(ct: String): RequestBuilder[A]
  def header(k: String, v: String): RequestBuilder[A]
  def body(...): SyncRequestBuilder[A]
  def response[B](rb: ResponseAs[B, Any]): RequestBuilder[B]
  // ...

  // “finalizers”
  def get(uri: Uri): Request[A]
  def post(uri: Uri): Request[A]
  // ...

}

trait Request[A] extends RequestT[Identity, A, Any] {
  def send(backend: SttpBackend[Identity, Any]): Response[A]
}
~~~

**Comment by julienrf** [comment]
I wonder if the backend parameter could even be omitted in the `send` method of `Request`, if the request was created by the backend itself:

~~~ scala
val client = SimpleHttpClient()
val request =
  client.basicRequest
    .body("Hello, world!")
    .post(uri"https://httpbin.org/post?hello=world")
val response = request.send()
~~~

**Comment by odersky** [comment]
I agree. We should never expose `RequestT`. it's a scary type that requires knowledge of Monad transformers to fully understand. An http client should never demand that level of knowledge, unless it is part of a category theory inspired library where such knowledge is a prerequisite.

**Comment by adamw** [comment]
@odersky I think there's a misunderstanding, there are no monad transformers involved at all :) `RequestT` stands for "RequestTemplate" and has been there since sttp v1 I think. I doubt we'll be able not to expose it as it's the central datastructre in sttp.

There are two aliases which are often used, though:

```scala
  /** A [[RequestT]] without the method & uri specified (which cannot yet be sent).  */
  type PartialRequest[T, -R] = RequestT[Empty, T, R]

  /** A [[RequestT]] with the method & uri specified. Such a request can be sent. */
  type Request[T, -R] = RequestT[Identity, T, R]
```

**Comment by adamw** [comment]
@julienrf `Request` is already taken by an alias to `RequestT`. We can try e.g. `SimpleRequest`, but keeping in mind:

1. we have to maintain binary compatibility
2. I wouldn't want the "simple" API to diverge to much from the "normal" one. We'll end up maintaining two libraries and two APIs inside of one binary - not something I'd like to do.

Note that synchronous requests can also leverage capabilities. Currently the default backend doesn't support any, but I hope to implement websocket support at some point in time. Streaming is also not out of the question, I think we could accept RS publishers as a body inside an otherwise synchronous request.

The whole point of `RequestT` is not to duplicate all the builder methods which allows describing the request. Whether this was a good decision might be up for debate of course, but it's there since sttp v1 and if at all, we could consider changing it in sttp v4. But providing a hybrid in a 3-point release isn't probably a good idea.

As for creating the request from the backend - again, it's a different API, which would yield a different library. We already have too many ways of sending requests (`request.send(backend)`; `backend.send(request)`; `simpleHttpClient.send(request)`). Adding yet another one would be only confusing. Plus, I don't think that's really doable, if we want to keep the data structure which describes the request the same for "synchronous"/"simple" and "normal" cases.

**Comment by odersky** [comment]
@adamw Ah, I misunderstood then. When I see an AbcT type that takes an higher-kinded type I always think Monad transformer, since the naming convention is so pervasive. 

For the Scala toolkit: I think it's a fairly big step to make a library part of it. So doing changes that need a major release seems reasonable to me.

**Comment by adamw** [comment]
@odersky I think I came up with the name quite long ago when I wasn't that familiar with the monad-related naming conventions :)

A major release with an improved API is of course possible, and suggestions are very welcome. However, I'd like to keep a single API, which works the same with synchronous & async requests. I think it's only an advantage if a library from the toolkit allows you to work with the same (or very similar) API in the "simple" cases and when using any of the effects used in Scala (Future, cats, ZIO). Looking at sonatype's stats, currently the vast majority of sttp's users use it with some kind of async backend - so it's not a public we should overlook :)

**Comment by szymon-rd** [comment]
Right now when a request is being constructed with `basicRequest`, the `RequestT` type does leak to the user in suggestions and types of expressions. I agree that it would be great to avoid that. If we were able to create some simple request builder that did not expose these types, I think it could lead to less confusion for users.

**Comment by julienrf** [comment]
> There are two aliases which are often used, though:
> 
> ```scala
>   /** A [[RequestT]] without the method & uri specified (which cannot yet be sent).  */
>   type PartialRequest[T, -R] = RequestT[Empty, T, R]
> 
>   /** A [[RequestT]] with the method & uri specified. Such a request can be sent. */
>   type Request[T, -R] = RequestT[Identity, T, R]
> ```

These aliases precisely expose the full `RequestT` type to the end users since they are “transparent” aliases.

> `Request` is already taken by an alias to `RequestT`. We can try e.g. `SimpleRequest`, but keeping in mind:
> 
>     1. we have to maintain binary compatibility
> 
>     2. I wouldn't want the "simple" API to diverge to much from the "normal" one. We'll end up maintaining two libraries and two APIs inside of one binary - not something I'd like to do.
> 
> 
> Note that synchronous requests can also leverage capabilities. Currently the default backend doesn't support any, but I hope to implement websocket support at some point in time. Streaming is also not out of the question, I think we could accept RS publishers as a body inside an otherwise synchronous request.
> 
> The whole point of `RequestT` is not to duplicate all the builder methods which allows describing the request. Whether this was a good decision might be up for debate of course, but it's there since sttp v1 and if at all, we could consider changing it in sttp v4. But providing a hybrid in a 3-point release isn't probably a good idea.
> 
> As for creating the request from the backend - again, it's a different API, which would yield a different library. We already have too many ways of sending requests (`request.send(backend)`; `backend.send(request)`; `simpleHttpClient.send(request)`). Adding yet another one would be only confusing. Plus, I don't think that's really doable, if we want to keep the data structure which describes the request the same for "synchronous"/"simple" and "normal" cases.

Thank you for the detailed explanation. I understand the concerns about binary compatibility and code duplication.

Indeed, what I suggest is to have another type `Request` that would be specific to the `SimpleHttpClient`. That would indeed be another API to maintain, given the current design of sttp.

I see value in keeping the ability to describe requests independently of a specific backend implementation (I use that in endpoints4s, for instance). However, I guess the typical workflow with sttp, for end-users, is to pick just one backend and send all their requests through that backend. This is why I would like to investigate whether it is possible to “optimize” the API in that direction. But my initial assumption might be wrong?

I think it is possible to create a new type `SimpleHttpClient.Request[A]` (along with `SimpleHttpClient.RequestBuilder[A]`), as I described above. Would you be open to that?

**Comment by adamw** [comment]
I would try to avoid creating a parallel API if possible. The whole point of sttp is that you create a data structure describing the request, and then you can send it using any backend (as long as it has the required capabilities).

If we were to create a separate synchronous-only API, then I think it would make more sense to publish it as a separate library, with its own lifecycle etc.

Another thing is all the integrations - even the most basic ones, redirects, observability, custom retry backends etc. - they all use the current API and would have to be duplicated. Not something I'd like to maintain :)

But that doesn't mean that some improved type hierarchy, maybe requiring a binary-incompatible change, which gives better synchronous requests support is not possible. However first, I'd like to gather some information if the `RequestT` is indeed a problem. One data point that I have, is that on the support channels that I participate in (gitter, issues), I think only once or twice there was a question about the type aliases and type parameters. Of course, my memory could be incomplete, or beginners might be discouraged and simply not ask.

Still, I'd like to run a more thorough process to see what are the problems with the current design before jumping to solutions :). But that's probably earliest in December.

**Comment by adamw** [comment]
Closing as this is implemented in sttp4, thanks for the comments!
