### ISSUE TITLE
Cannot decode `Option[T]` from 204 No Content responses

### ISSUE THREAD

**Issue by mkubala** [softwaremill/sttp#161]
Sometimes I need to consume HTTP APIs that (depending on some circumstances) can respond with 204 status and no content.

I've been trying to handle this case using `.response(asJson[Option[T]])` which unfortunately leads to `Left(DeserializationError(,io.circe.ParsingFailure: exhausted input,ParsingFailure: exhausted input))` while using Circe.

I don't know if this issue affects also other serializers (I've been using STTP only with Circe so far..) but as long as there is no sensible reason for keep deserialization failing on the above case I'd like to provide appropriate tests cases for all of them and ensure that their behaviour is consistent.

**Comment by adamw** [comment]
I'm wondering if there's any sensible situation where you could have valid top-level json that deserializes to `None`. I suppose `null` would be one such case - but is it valid top-level json at all? Opinons differ ;) (https://stackoverflow.com/questions/7487869/is-this-simple-string-considered-valid-json)

So:
* if there's no top-level json that could be represented as `None`, then it's a no-brainer - in such case, we should deserialize an empty string to `None`
* otherwise, I don't know :)

**Comment by adamw** [comment]
Re: your proposed solution for is-option checking: https://gist.github.com/mkubala/a4f7da1c3cf00a96221901de057e0f1a

Manifests have the downside that they sometimes aren't there, e.g. for tagged types, primitives, and some other cases which I can't recall ;)

But maybe the following would work?

```
object X extends App {
  trait Tag[+U] extends Any { type Tag <: U }
  type @@[+T, +U]     = T with Tag[U]

  trait IsOption[T] { def isOption: Boolean }
  object IsOption {
    implicit def optionIsOption[T <: Option[_]]: IsOption[T] = new IsOption[T] { override val isOption = true }
    implicit def otherIsNotOption[T]: IsOption[T] = new IsOption[T] { override val isOption = false }
  }

  println(implicitly[IsOption[String]].isOption)
  println(implicitly[IsOption[List[String]]].isOption)
  println(implicitly[IsOption[Option[String]]].isOption)
  println(implicitly[IsOption[Option[String] @@ Int]].isOption)
  println(implicitly[IsOption[None.type]].isOption)
}
```
(as a typeclass for is-option checking)

**Comment by mkubala** [comment]
I thought that introducing our own type class here will be an overkill, although it seems to be only way to go given that `Option` might be tagged (or wrapped in `Either`).

Also I'm glad that everything will be done at compile time 🎉

Expect a PR soon 👍

**Comment by shrynx** [comment]
Hi ! i am on version `2.2.9` and am still seeing this bug

**Comment by adamw** [comment]
@shrynx can you provide some more details - which interpreter, which json library, some example code to reproduce?

**Comment by shrynx** [comment]
Sorry false alarm

well, when response type is parameterised it doesn't work by default

```scala
import io.circe._
import sttp.client._
import sttp.client.circe._
import sttp.model.Uri

trait ApiClient {
  implicit val backend: SttpBackend[Identity, Nothing, NothingT] = HttpURLConnectionBackend()

  def sendPost[Body: Encoder, Result: Decoder](url: Uri, body: Body) =
    basicRequest.body(body).post(url)
      .response(asJson[Result])
      .send()
}

object MyClient extends ApiClient {
  def httpBin204 = sendPost[None.type, Option[Json]](uri"https://httpbin.org/status/204", None)
}

println(s"result is | ${MyClient.httpBin204}")
```

```
// Response(Left(sttp.client.DeserializationError: exhausted input)
```

but adding `IsOption` to resp type fixes it

```scala
  def sendPost[Body: Encoder, Result: Decoder : IsOption](url: Uri, body: Body) = 
``` 
```
// Response(Right(None),204,NO CONTENT, .....
```

**Comment by adamw** [comment]
@shrynx Yeah, `IsOption` is the mechanism that needs to be used here. There's a fallback instance for any `T`, which gets picked if no other implicit is available in scope, which happens when you just have a generic `T`.

Maybe a more robust solution would be to just check if the value is a `None`, instead of the typeclass - but for that, please create a separate issue
