### ISSUE TITLE
Sttp starts a ForkJoinPool.commonPool-worker - can you explain why?

### ISSUE THREAD

**Issue by don41382** [softwaremill/sttp#1707]
Hi guys,

Thanks for the awesome library. I just have a quick question. I noticed when sending a request, sttp starts a `ForkJoinPool.commonPool-worker` and I don't understand why.

I thought by passing in an ExecutionContext it would only use that one.

Here is the sample program:
```
import sttp.client3.{HttpClientFutureBackend, UriContext, basicRequest}

import java.util.concurrent.Executors
import scala.concurrent.{Await, ExecutionContext}
import scala.concurrent.duration.DurationInt

object SttpTest extends App {

  val ec = ExecutionContext.fromExecutor(Executors.newSingleThreadExecutor())
  val backend = HttpClientFutureBackend()(ec)
  val result = basicRequest.get(uri"https://www.google.de").send(backend)

  Await.result(result, 10.seconds)
}
```

VisualVM View
<img width="620" alt="image" src="https://user-images.githubusercontent.com/1768764/213392806-9c64f52f-2147-4d54-9f8b-50b11008bb8c.png">

I am using the latest version `3.8.8` with Scala `2.13.10`. I would love to understand, why this is happening / needed. 

Thanks in advance!

**Comment by adamw** [comment]
This thread seems to be always started when using HttpClient: https://github.com/openjdk/jdk/blob/master/src/java.net.http/share/classes/jdk/internal/net/http/HttpClientImpl.java#L507-L531

As far as I understand, that's the thread that waits for the socket which has data to read, and then any processing is delegated to the provided executor.

**Comment by don41382** [comment]
@adamw Understood. But what about the `ForkJoinPool.commonPool-woker`. Do you know where this pool is coming from?

**Comment by adamw** [comment]
@don41382 that was more tricky, there are in fact two reasons:

1. https://github.com/openjdk/jdk/blob/master/src/java.net.http/share/classes/jdk/internal/net/http/HttpClientImpl.java#L990-L995

Not sure why this `if` exists, but it causes the default FJ pool to initialise (and run a dummy operation). Not sure if there's a way to escape it - the `exchangeExecutor` is not `null`, as we're setting it to our executor explicitly

2. in sttp itself: https://github.com/softwaremill/sttp/blob/2a1a478bac29e4a9bdb57369e0b62653d1c02b88/core/src/main/scalajvm/sttp/client3/HttpClientAsyncBackend.scala#L44

this could be replaced by `.whenCompleteAsync`, providing the executor, however when doing so with the single-threaded one, everything hangs (on some locks). I didn't debug this, but the async operations get in some kind of deadlock. However even with this change, the FJ pool is already initialised before control is returned to sttp because of (1)

**Comment by adamw** [comment]
Regarding (2), I've been able to optimize the way we use read the body as an input stream (which happens when using the `Future`-based backend, however even then, the 1-threaded scenario hangs, because there's a blocking queue involved at the JDK level: https://github.com/openjdk/jdk/blob/master/src/java.net.http/share/classes/jdk/internal/net/http/ResponseSubscribers.java#L412

As the way the response is parsed is dynamic, we need to read the response into a low-level representation, such as an `InputStream`. So I don't think further fixes are possible here.

**Comment by adamw** [comment]
FYI I've posted a question on SO to try to better understand how `HttpClient` works in this scenario: https://stackoverflow.com/questions/75246754/why-is-the-default-fork-join-pool-always-started-when-sending-a-request-using-jd

**Comment by don41382** [comment]
Thanks @adamw for posting this question and your engagement on this tooic. 

Do you think it would make sense to allow passing two EC? One for the blocking and one for your mentioned Input Stream Raw parsing, which probably is more CPU bound. 

And what is the use case for just passing one thread EC or is this just for dead lock safety?

**Comment by adamw** [comment]
Right now, all blocking calls are properly scoped using `scala.concurrent.blocking`, so this should spawn new threads if necessary. I don't think passing two ECs would make sense here.

> And what is the use case for just passing one thread EC or is this just for dead lock safety?

I don't know, that's from your original example :)
