### ISSUE TITLE
No way to handle Invalid header value using HttpClientZioBackend

### ISSUE THREAD

**Issue by vitaliihonta** [softwaremill/sttp#1823]
## Reproducer 

Requires `"com.softwaremill.sttp.client3" %% "zio" % "3.8.15"`
[Scastie link](https://scastie.scala-lang.org/DWNCO04cRDaqdR2evcLOzw) to the same code.

```scala
import zio._
import sttp.client3._
import sttp.client3.httpclient.zio.HttpClientZioBackend

object Main extends ZIOAppDefault {

  val program = for {
    backend  <- HttpClientZioBackend.scoped()
    response <- basicRequest.get(uri"https://example.com")
       // the problem is here
      .header("X-Api-Key", "Я ЛЮБЛЮ БОРЩ")
      .response(asString)
      .send(backend)
  } yield ()

  val run = program
    .catchAllDefect { defect =>
       // It should have been an error?
       ZIO.consoleWith(_.printLine(s"Captured defect=$defect"))
    }
}
```

## Actual console output:
```
Captured defect=java.lang.IllegalArgumentException: invalid header value: "Я ЛЮБЛЮ БОРЩ"
```

## Expectation:
While non-latin header values are forbidden, it's confusing that such an error is a ZIO defect. 
What is more confusing is that sttp doesn't provide a proper way to validate the header value. 
Therefore, there is no way to overcome this error easily.

I'd expect there is a way to either validate the header or handle such errors as ZIO's errors, because the header value may be a user input (therefore, it may be incorrect).

Is there any reason why this invalid header value isn't handled as "normal" error, but as a defect?

**Comment by adamw** [comment]
I think there are two problems here:

1. sttp model contains methods for creating the model classes w/ validation (as described [here](https://github.com/softwaremill/sttp-model#project-content)), however for some reason the header value is not validated (while it should, along the rules specified [here](https://www.rfc-editor.org/rfc/rfc9110.html#name-field-values)). So we should fix this, so that `.header(Header.unsafeApply("X-Api-Key", "Я ЛЮБЛЮ БОРЩ"))` would behave as expected (throw a validation error)
2. as for defects/errors, throwing an exception inside a `.map` in ZIO is translated to a defect (e.g. `ZIO.succeed(1).map(_ => throw new IllegalArgumentException(""))`). That's just how ZIO works ... but as we want to represent any exceptions that happen during request construction as errors, I think that all ZIO backends should override `.send` and additionaly do:

```
    .catchSomeDefect {
      case e: Exception => ZIO.fail(e)
    }
```
