### ISSUE TITLE
Update to Prometheus 1.x.x

### ISSUE THREAD

**Issue by KarelCemus** [softwaremill/sttp#2011]
Prometheus made [incompatible changes in v1.x.x](https://github.com/prometheus/client_java/releases) and some libraries such as Tapir already migrated to the latest version of Prometheus so it would be helpful to update this project also into latest Prometheus to allow use of Tapir with sttp backend.

Right now, this project still depends on Prometheus v0.x.x [code](https://github.com/softwaremill/sttp/blob/ee57f39d5222aa7abcbae27b7e1ccfbc5e516d17/build.sbt#L918).

**Comment by andreazube** [comment]
Unfortunately, there are some serious breaking change in the 1.x line.

For example, as far as I can tell it's no longer possible to provide custom buckets for histograms, a functionality that was previously there and sttp exposed to the user. So, if I'm understanding it correctly, updating prometheus will also imply a breaking change in sttp. Not sure how far away sttp4 is from being released, but it could be it'll be the only version with the new prometheus client.

I quickly tried to update the dependency myself in a fork, but because gave up because of the above - the upgrade isn't big per se, but requires some choices that will impact sttp's API.

---

In the meantime, what you can do in your own project is add the [simpleclient bridge](https://prometheus.github.io/client_java/migration/simpleclient/#migration-using-the-simpleclient-bridge). 

This at least makes sttp and tapir work together nicely again, but it's of course a temporary solution until sttp is able to use prometheus-client 1.x

**Comment by adamw** [comment]
Maybe we can update to 1.x.x in sttp4, and keep the old version in sttp3, wdyt?

**Comment by Awethon** [comment]
I might be wrong but classicUpperBounds method in histogram builder is suitable to make custom buckets.
I hope sttp4 will be released soon, didn't expect tapir and sttp dependencies to diverge.
