### ISSUE TITLE
How to integrate scalajs + sttp + ox

### ISSUE THREAD

**Issue by gvlpedro** [softwaremill/sttp#2266]
Hi, my goal is to create an extension of the example Ox websocket with scalajs to do a chat, I saw a good example [here](https://github.com/softwaremill/sttp/blob/master/examples3/src/main/scala/sttp/client4/examples/WebSocketOx.scala) but when I use ox from my frontend/scalajs module (  "com.softwaremill.sttp.client4" %%% "ox"  % "4.0.0-M17" )  there isn't a library for scala js calls, I think I am little bit lost in this scala universe, I assume this is not possible because is not implemented yet but I would like to ask here to see if I am right or thiere is an alternative.

Thank you in advance.

**Comment by adamw** [comment]
Ox is unfortunately not available for Scala.JS, and won't be - because the JS execution model is inherently single-threaded and callback-based. So on the JS side, you'll need to use the `Future`-based APIs, or some of the "functional" ones. There's some more information here: https://sttp.softwaremill.com/en/latest/backends/javascript/fetch.html

**Comment by gvlpedro** [comment]
thank you, it was very clear :)
