### ISSUE TITLE
Example with exception from sttp testing docs causes "dead code following this construct" warning

### ISSUE THREAD

**Issue by DenisNovac** [softwaremill/sttp#816]
There is an example for simulating exceptions in stub backend where you need to throw an exception which causes dead code warning or error (with tpolecat plugin).

URL: https://sttp.softwaremill.com/en/latest/testing.html#simulating-exceptions

```scala
val testingBackend = SttpBackendStub.synchronous
  .whenRequestMatches(_ => true)
  .thenRespond(throw new SttpClientException.ConnectException(
    basicRequest.get(uri"http://example.com"), new RuntimeException))
```

Warning:

```
dead code following this construct
          throw new SttpClientException.ConnectException(
```

Perhaps it should have some specific methods for simulating errors like:

```scala
val testingBackend = SttpBackendStub.synchronous
  .whenRequestMatches(_ => true)
  .respondWithError(...)
```

**Comment by adamw** [comment]
But isn't it a problem in the compiler, with a false warning, rather than a problem in the API?

There is already `thenRespondServerError`, but this completest the request successfully, but with a 503 response code. There's also `thenRespondF`, where you can return a failed effect (instead of throwing an exception)

**Comment by DenisNovac** [comment]
I thought it was some problem with `thenRespond` since i have no such warning in other places with `throw`. It's work well with `thenRespondF(IO.raiseError(...))` or with `MonadError[F].error`.
